MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  #PRETRAIN_PATH: 'path to pre-trained ResNet50 .pth file'
  PRETRAIN_PATH: 'path to pre-trained DenseNet201 .pth file'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'yes'
  NAME: 'resnet50'
  #NAME: 'densenet'

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('jaguar')
  ROOT_DIR: ('data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.0001

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 24

  STEPS: [30, 70]
  GAMMA: 0.01

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 10
  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 16
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "jaguar_test"


